/******************************************************
**MÔN BẢO MẬT CƠ SỞ DỮ LIỆU LAB 03 NHÓM 10
**Store procedure: Câu đăng nhập và màn hình sinh viên
**Author: vnqmai
*******************************************************/

--USE DATABASE QLSV
--GO

--THÊM SINH VIÊN CÓ MẬT KHẨU HASH SHA1 VÀO DB
INSERT INTO SINHVIEN VALUES('SV01','NGUYEN VAN A','1/1/1990','280 ANDUONG VUONG', 'CNTT-K35', 'NVA',HASHBYTES('SHA1',CAST('123456' AS varbinary(Max))))
INSERT INTO SINHVIEN VALUES('SV02','NGUYEN VAN A','1/1/1990','222 LE VAN SI', 'L01', 'LTB',HASHBYTES('SHA1',CAST('123456' AS varbinary(Max))))

--CÂU ĐĂNG NHẬP
CREATE PROC KIEMTRATAIKHOAN (@TENDN NVARCHAR(100), @MATKHAU VARCHAR(100))
AS
BEGIN
	IF EXISTS (SELECT * FROM SINHVIEN WHERE TENDN = @TENDN AND MATKHAU = HASHBYTES('SHA1',@MATKHAU))
		RETURN 1
	ELSE IF EXISTS (SELECT * FROM NHANVIEN WHERE TENDN = @TENDN AND MATKHAU = HASHBYTES('SHA1',@MATKHAU))
		RETURN -1
	ELSE
		RETURN 0
END

--CÂU MÀN HÌNH SINH VIÊN
CREATE PROC UPDATESV (@MASV NVARCHAR(20),@HOTEN NVARCHAR(100),@NGAYSINH DATETIME, @DIACHI NVARCHAR(200),@MALOP VARCHAR(20),@TENDN NVARCHAR(100),@MATKHAU VARCHAR(MAX))
AS
BEGIN
	UPDATE SINHVIEN
	SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH, DIACHI = @DIACHI, MALOP = @MALOP,TENDN = @TENDN, MATKHAU = HASHBYTES('SHA1',@MATKHAU)
	WHERE MASV = @MASV
END

CREATE PROC UPDATESV_KHONGMATKHAU (@MASV NVARCHAR(20),@HOTEN NVARCHAR(100),@NGAYSINH DATETIME, @DIACHI NVARCHAR(200),@MALOP VARCHAR(20),@TENDN NVARCHAR(100))
AS
BEGIN
	UPDATE SINHVIEN
	SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH, DIACHI = @DIACHI, MALOP = @MALOP,TENDN = @TENDN
	WHERE MASV = @MASV
END



